export const SUBCATEGORIES = [
  "Attar",
  "Air Freshener",
  "Briefs",
  "Blazers",
  "Boxers",
  "Bath Towels",
  "Bathroom Accessories",
  "Baby Gear & Nursery",
  "Bodysuit",
  "Backpacks",
  "Co-Ords",
  "Clothing Fabric",
  "Clothing Set",
  "Coats",
  "Churidar",
  "Cleaning Cloth",
  "Capris",
  "Chair Cover",
  "Camisoles",
  "Caps",
  "Curtains and Sheers",
  "Clutches",
  "Clocks",
  "Ceiling Lamps",
  "Dhotis",
  "Dupatta",
  "Dungarees",
  "Duffel Bag",
  "Dresses",
  "Decals and Stickers",
  "Electric Barbecue",
  "Festive Decor",
  "Face Shield",
  "Fragrance Gift Set",
  "Facial Wipes and Tissues",
  "Face Towels",
  "Gloves",
  "Garden Accessories",
  "Harem Pants",
  "Hooks and Holders",
  "Hanger",
  "Headband",
  "Hand Towels",
  "Hammock Swing",
  "Innerwear Vests",
  "Jeans",
  "Jackets",
  "Jumpsuit",
  "Kurtas",
  "Kurta Sets",
  "Kitchen Towels",
  "Kurtis",
  "Kitchen Linen Sets",
  "Key Holders",
  "Lounge Pants",
  "Lounge Tshirts",
  "Lounge Shorts",
  "Lingerie accessories",
  "Lungi",
  "Laundry Bag",
  "Leggings",
  "Makeup Remover",
  "Massage Oils",
  "Nehru Jackets",
  "Night suits",
  "Organisers",
  "Outdoor Masks",
  "Other Kitchen Tools",
  "Pyjamas",
  "Pooja Essentials",
  "Perfume",
  "Palazzos",
  "Patiala",
  "Rain Suit",
  "Rain Jacket",
  "Robe",
  "Rain Trousers",
  "Racks and Wardrobes",
  "Runners",
  "Shirts",
  "Sweatshirts",
  "Shorts",
  "Sweaters",
  "Suits",
  "Sherwani",
  "Shawl",
  "Shackets",
  "Swim Bottoms",
  "Shapewear",
  "Swimwear",
  "Salwar",
  "Shrug",
  "Swim Tops",
  "Shoe Care",
  "Skirts",
  "Stationery",
  "Scarves",
  "Swimwear Cover up Top",
  "Sofa Covers",
  "Swimwear Cover up Bottom",
  "Tshirts",
  "Trousers",
  "Track Pants",
  "Trunk",
  "Tracksuits",
  "Thermal Tops",
  "Thermal Bottoms",
  "Thermal Set",
  "Tights",
  "Table Covers",
  "Tops",
  "Tunics",
  "Table Napkins",
  "Table Linen Sets",
  "Watches",
  "Waistcoat",
  "Wall Art",
  "Wall Decor"
].sort();
